# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'ATX Open Data'
tagline:          'ATX Open Data Initiative'
description:      ''
url:              
baseurl:          https://cityofaustin.github.io/open-data-docs/

author:
  name:           ''
  url:            ''

paginate:         5

gems:             [jekyll-paginate]
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cityofaustin/open-data-docs
